version: '3'

services:
  server:
    build:
      context: ./
      dockerfile: ./Dockerfile
    restart: always
    environment:
      PORT: ${PORT}
      MARIADB_HOSTNAME: mariadb
    volumes:
      - ./:/app
    expose:
      - "80"
      - "6060"
    ports:
      - "1323:1323"
    depends_on:
      - mariadb

  mariadb:
    image: mariadb:latest
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: asset-manager
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_general_ci
    volumes:
      - ./mysql/data:/var/lib/mysql:z
      - ./mysql/init:/docker-entrypoint-initdb.d:z

  phpmyadmin:
    depends_on:
      - mariadb
    container_name: assetmanager_phpmyadmin
    image: phpmyadmin:latest
    environment:
      PMA_HOST: mariadb
      PMA_PORT: 3306
      PMA_USER: root
      PMA_PASSWORD: password
    ports:
      - "8080:80"
